### ISSUE TITLE
Turn off scheduled CRON builds from Travis

### ISSUE THREAD

**Issue by netj** [vochicong/deepdive#2]
@vochicong Can you please turn off the daily build from https://travis-ci.org/vochicong/deepdive?  deepdive-dev@googlegroups is getting the same build message over and over again.  Thanks!

**Comment by vochicong** [comment]
@netj I've turned off the daily build from Travis CI. 

Just wonder if we can set the notification email as a Travis CI environment variable?
https://github.com/vochicong/deepdive/blob/master/.travis.yml#L12

**Comment by netj** [comment]
Thanks!  I don't know if Travis supports env vars in that place but that'd be nice to have.  We did not encounter this problem as most forks weren't using Travis.  Feel free to create a PR.  I can move the address to Travis CI.

**Comment by vochicong** [comment]
@netj You're welcome!

It's not possible setting notification email as env vars:
https://github.com/travis-ci/travis-ci/issues/2711

They are going to [move notification settings to the website](https://github.com/travis-ci/travis-ci/issues/1094).
